// <auto-generated />
namespace Online_Shopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removenamefromSalesinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removenamefromSalesinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "202308031058378_remove name from Sales-info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
