// <auto-generated />
namespace Online_Shopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removequantiyfromproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removequantiyfromproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202307302138255_remove quantiy from product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
