// <auto-generated />
namespace Online_Shopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddSalecodetoonrouteandverifiedsale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSalecodetoonrouteandverifiedsale));
        
        string IMigrationMetadata.Id
        {
            get { return "202308010925286_Add Salecode to onroute and verified sale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
